language: csharp
mono: none
dotnet: 2.2.101
os: linux
dist: xenial

install:
- dotnet restore src/NextCourses.csproj

script:
- dotnet build src/NextCourses.csproj
- dotnet test tests/UnitTests.csproj
 